name: Deploy to production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    environment:
      name: lisn
    steps:
      - uses: actions/checkout@v1
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
          ls
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source : "deploy.tar"
          overwrite: true
          target: ${{ secrets.WORK_DIR }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          script: cd ${{ secrets.WORK_DIR }} && tar -xvf deploy.tar && rm deploy.tar
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
